config/routes.rb
# config/routes.rb


Rails.application.routes.draw do
  root 'home#index'                   # Root URL (home page)
  get 'about', to: 'pages#about'      # About page
  get 'projects', to: 'pages#projects'  # Projects page
  get 'contact', to: 'pages#contact'  # Contact page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def send_contact
    name = params[:name]
    email = params[:email]
    message = params[:message]

    # Implement email sending functionality here

    flash[:notice] = "Thank you for your message!"
    redirect_to contact_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def projects
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :technologies, :role, :challenges, :live_link, :source_code_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->



<div class="jumbotron">
  <h1 class="display-4">Hello, I'm Nicole McInerney!</h1>
  <p class="lead">Welcome to my portfolio. I'm a Fullstack Web Developer.</p>
  <hr class="my-4">
  <p>Check out my projects and learn more about me.</p>
  <%= link_to 'View Projects', projects_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'About Me', about_path, class: 'btn btn-secondary btn-lg' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPortfolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'header', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lucida+Console&display=swap">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
  <header class="header">
    <div class="header__content">
      <div class="header__photo-container">
        <img src="<%= asset_path('myphoto.png') %>" alt="Your Logo" class="header__photo" />
        <h2 class="header__title">Nicole McInerney</h2>
      </div>
      <nav class="header__main">
        <ul class="header__links">
          <li class="header__link-wrapper">
            <%= link_to 'Home', root_path, class: 'header__link' %>
          </li>
          <li class="header__link-wrapper">
            <%= link_to 'About', about_path, class: 'header__link' %>
          </li>
          <li class="header__link-wrapper">
            <%= link_to 'Projects', projects_path, class: 'header__link' %>
          </li>
          <li class="header__link-wrapper">
            <%= link_to 'Contact', contact_path, class: 'header__link' %>
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="sidebar">
    <ul class="sidebar__links">
      <li class="sidebar__link-wrapper">
        <a href="https://www.linkedin.com/in/nicolemci/" target="_blank" class="sidebar__link">
          <i class="fab fa-linkedin"></i>
        </a>
      </li>
      <li class="sidebar__link-wrapper">
        <a href="https://www.youtube.com/channel/UCwz6UD3eiUmVGIK7Gbtok_A" target="_blank" class="sidebar__link">
          <i class="fab fa-youtube"></i>
        </a>
      </li>
      <li class="sidebar__link-wrapper">
        <a href="https://github.com/Nicolemci" target="_blank" class="sidebar__link">
          <i class="fab fa-github"></i>

      </li>
    </ul>
  </div>

  <div class="container">
    <div class="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>Hi, I'm Nicole. I'm a Backend Web Developer with experience in Ruby, CSS, HTML, JavaScript, SQL.</p>
<p>Here's a bit more about me...</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>This is the Contact page.</p>
add linkedin
email address
phone number
<a href="https://www.linkedin.com/in/nicolemci" target="_blank">
   <img src="path-to-linkedin-icon.png" alt="LinkedIn Profile">

   <h1>Contact Me</h1>

<%= form_with url: contact_path, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: 'form-control' %>
  </div>
  <%= form.submit 'Send Message', class: 'btn btn-primary' %>
<% end %>
</a>

app/views/pages/projects.html.erb
<h1>Projects</h1>
<p>This is the Projects page.</p>

add game, budget and trading bot

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :technologies, style: "display: block" %>
    <%= form.text_field :technologies %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :challenges, style: "display: block" %>
    <%= form.text_area :challenges %>
  </div>

  <div>
    <%= form.label :live_link, style: "display: block" %>
    <%= form.text_field :live_link %>
  </div>

  <div>
    <%= form.label :source_code_link, style: "display: block" %>
    <%= form.text_field :source_code_link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Technologies:</strong>
    <%= project.technologies %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= project.role %>
  </p>

  <p>
    <strong>Challenges:</strong>
    <%= project.challenges %>
  </p>

  <p>
    <strong>Live link:</strong>
    <%= project.live_link %>
  </p>

  <p>
    <strong>Source code link:</strong>
    <%= project.source_code_link %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<!-- app/views/projects/index.html.erb -->
<h1>Projects</h1>

<div class="row">
  <% @projects.each do |project| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= project.title %></h5>
          <p class="card-text"><%= truncate(project.description, length: 100) %></p>
          <%= link_to 'View Project', project, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<!-- app/views/projects/show.html.erb -->
<h1><%= @project.title %></h1>

<p><%= @project.description %></p>
<p><strong>Technologies:</strong> <%= @project.technologies %></p>
<p><strong>Role:</strong> <%= @project.role %></p>
<p><strong>Challenges:</strong> <%= @project.challenges %></p>
<p><strong>Live Link:</strong> <%= link_to @project.live_link, @project.live_link %></p>
<p><strong>Source Code:</strong> <%= link_to 'GitHub', @project.source_code_link %></p>

<%= link_to 'Back to Projects', projects_path, class: 'btn btn-secondary' %>